[project]
name = "APITestGen"
version = "0.1.0"
description = "API测试用例自动生成工具 | API Test Cases Auto Generator"
authors = [
    {name = "tushanxing", email = "tushanxing1995@gmail.com"},
]
dependencies = ["orjson>=3.11.3",
                "pysimdjson>=7.0.2",
                "pytest>=8.4.2"]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}
scripts = {apitestgen = "apitestgen.cli.cli:main"}

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "-e file:///${PROJECT_ROOT}/#egg=APITestGen",
]